/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package rodrigoservicecenter.views;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author navee
 */
public class RegisterPanel extends javax.swing.JInternalFrame {

    /**
     * Creates new form Register
     */
    public RegisterPanel() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); 
        BasicInternalFrameUI ui= (BasicInternalFrameUI) this.getUI(); 
        ui.setNorthPane (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        MyTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        MyTextField1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        MyTextField2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        MyTextField3 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        MyTextField4 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        MyTextField5 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1240, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rodrigoservicecenter/resources/4.png"))); // NOI18N
        jLabel2.setText("register");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 340, 170));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("Welcome to Rodrigo Service Center");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setText("New Customer");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jLabel15.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        MyTextField.setText("Enter name");
        MyTextField.setActionCommand("null");
        MyTextField.setBorder(null);
        MyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(MyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 360, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 360, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 140, -1));

        MyTextField1.setText("E-mail");
        MyTextField1.setActionCommand("null");
        MyTextField1.setBorder(null);
        MyTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(MyTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 360, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 360, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("E-mail");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 140, -1));

        MyTextField2.setText("Address");
        MyTextField2.setActionCommand("null");
        MyTextField2.setBorder(null);
        MyTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(MyTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 360, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 360, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 160, -1));

        MyTextField3.setText("Enter name");
        MyTextField3.setActionCommand("null");
        MyTextField3.setBorder(null);
        MyTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(MyTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 360, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 360, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("NIC");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, -1));

        MyTextField4.setText("Vehicles");
        MyTextField4.setActionCommand("null");
        MyTextField4.setBorder(null);
        MyTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(MyTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 360, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 360, 10));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Vehicles");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 160, -1));

        jButton8.setBackground(new java.awt.Color(0, 51, 153));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Register");
        jButton8.setBorder(null);
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 360, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 204));
        jLabel17.setText("NIMAL");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, -1, -1));

        MyTextField5.setText("Enter name");
        MyTextField5.setActionCommand("null");
        MyTextField5.setBorder(null);
        MyTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(MyTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 360, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 360, 10));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Mobile Number");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyTextFieldActionPerformed

    private void MyTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyTextField1ActionPerformed

    private void MyTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyTextField2ActionPerformed

    private void MyTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyTextField3ActionPerformed

    private void MyTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyTextField4ActionPerformed

    private void MyTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyTextField5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MyTextField;
    private javax.swing.JTextField MyTextField1;
    private javax.swing.JTextField MyTextField2;
    private javax.swing.JTextField MyTextField3;
    private javax.swing.JTextField MyTextField4;
    private javax.swing.JTextField MyTextField5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
