/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package rodrigoservicecenter.views;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author navee
 */
public class SellPanel extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainPart
     */
    public SellPanel() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); 
        BasicInternalFrameUI ui= (BasicInternalFrameUI) this.getUI(); 
        ui.setNorthPane (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        total_price = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        items = new javax.swing.JTable();
        payment = new javax.swing.JTextField();
        buy_bt = new javax.swing.JButton();
        quantity = new javax.swing.JSpinner();
        add_bt = new javax.swing.JButton();
        selected_delete_bt = new javax.swing.JButton();
        selected_clear_bt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        selected_item_quantity = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        Item_search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mobile_number = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        refresh_bt_2 = new javax.swing.JButton();
        refresh_bt_1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1240, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("quantity :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 120, 30));

        total_price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        total_price.setForeground(new java.awt.Color(102, 102, 102));
        total_price.setText("23 000");
        getContentPane().add(total_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 460, 80, 30));

        items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(items);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 500, 490));
        getContentPane().add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, 380, 30));

        buy_bt.setBackground(new java.awt.Color(0, 51, 153));
        buy_bt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buy_bt.setForeground(new java.awt.Color(255, 255, 255));
        buy_bt.setText("Pay Now");
        buy_bt.setBorder(null);
        buy_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_btActionPerformed(evt);
            }
        });
        getContentPane().add(buy_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 600, 110, 30));
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 80, 30));

        add_bt.setBackground(new java.awt.Color(0, 51, 153));
        add_bt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add_bt.setForeground(new java.awt.Color(255, 255, 255));
        add_bt.setText("ADD");
        add_bt.setBorder(null);
        add_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btActionPerformed(evt);
            }
        });
        getContentPane().add(add_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 110, 30));

        selected_delete_bt.setBackground(new java.awt.Color(255, 51, 51));
        selected_delete_bt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selected_delete_bt.setForeground(new java.awt.Color(255, 255, 255));
        selected_delete_bt.setText("Delete");
        selected_delete_bt.setBorder(null);
        selected_delete_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selected_delete_btActionPerformed(evt);
            }
        });
        getContentPane().add(selected_delete_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, 110, 30));

        selected_clear_bt.setBackground(new java.awt.Color(255, 51, 51));
        selected_clear_bt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selected_clear_bt.setForeground(new java.awt.Color(255, 255, 255));
        selected_clear_bt.setText("Clear");
        selected_clear_bt.setBorder(null);
        selected_clear_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selected_clear_btActionPerformed(evt);
            }
        });
        getContentPane().add(selected_clear_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 110, 30));

        selected_item_quantity.setColumns(20);
        selected_item_quantity.setRows(5);
        jScrollPane2.setViewportView(selected_item_quantity);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 540, 340));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Selected Items And Quantity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 280, 30));
        getContentPane().add(Item_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 310, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Mobile Number :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 170, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Payment   :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 140, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Total Amount :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 140, 30));
        getContentPane().add(mobile_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 380, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Search item :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, 30));

        refresh_bt_2.setForeground(new java.awt.Color(102, 102, 102));
        refresh_bt_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rodrigoservicecenter/resources/refresh-3104 (1).png"))); // NOI18N
        getContentPane().add(refresh_bt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, 30, 30));

        refresh_bt_1.setForeground(new java.awt.Color(102, 102, 102));
        refresh_bt_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rodrigoservicecenter/resources/refresh-3104 (1).png"))); // NOI18N
        refresh_bt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_bt_1ActionPerformed(evt);
            }
        });
        getContentPane().add(refresh_bt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 30, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buy_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buy_btActionPerformed

    private void selected_delete_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selected_delete_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selected_delete_btActionPerformed

    private void selected_clear_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selected_clear_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selected_clear_btActionPerformed

    private void refresh_bt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_bt_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refresh_bt_1ActionPerformed

    private void add_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_btActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Item_search;
    private javax.swing.JButton add_bt;
    private javax.swing.JButton buy_bt;
    private javax.swing.JTable items;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mobile_number;
    private javax.swing.JTextField payment;
    private javax.swing.JSpinner quantity;
    private javax.swing.JButton refresh_bt_1;
    private javax.swing.JButton refresh_bt_2;
    private javax.swing.JButton selected_clear_bt;
    private javax.swing.JButton selected_delete_bt;
    private javax.swing.JTextArea selected_item_quantity;
    private javax.swing.JLabel total_price;
    // End of variables declaration//GEN-END:variables
}
